#include "StartupWindow.h"
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QFileDialog>
#include <QMessageBox>
#include <QDir>
#include <QFile>
#include <QShortcut>
#include <QJsonDocument>
#include <QJsonObject>


StartupWindow::StartupWindow(QWidget *parent)
    : QWidget(parent)
{
    setWindowTitle("Create TangleML Project");
    setFixedSize(400, 200);

    nameEdit = new QLineEdit;
    nameEdit->setPlaceholderText("Project Name");

    pathEdit = new QLineEdit;
    pathEdit->setPlaceholderText("Project Folder");

    browseButton = new QPushButton("Browse");

    createButton = new QPushButton("Create Project");
    createButton->setEnabled(false);

    QShortcut *enterShortcut = new QShortcut(QKeySequence(Qt::Key_Return), this);
    connect(enterShortcut, &QShortcut::activated, createButton, &QPushButton::click);

    QVBoxLayout *layout = new QVBoxLayout;

    layout->addWidget(new QLabel("Project Name:"));
    layout->addWidget(nameEdit);

    layout->addWidget(new QLabel("Project Location:"));

    QHBoxLayout *h = new QHBoxLayout;
    h->addWidget(pathEdit);
    h->addWidget(browseButton);
    layout->addLayout(h);

    layout->addStretch();
    layout->addWidget(createButton);

    setLayout(layout);

    connect(browseButton, &QPushButton::clicked, this, &StartupWindow::browseFolder);
    connect(createButton, &QPushButton::clicked, this, &StartupWindow::createProject);
    connect(nameEdit, &QLineEdit::textChanged, this, &StartupWindow::validateInputs);
    connect(pathEdit, &QLineEdit::textChanged, this, &StartupWindow::validateInputs);
}

void StartupWindow::browseFolder() {
    QString folder = QFileDialog::getExistingDirectory(this, "Select Folder");
    if (!folder.isEmpty()) {
        pathEdit->setText(folder);
    }
}

void StartupWindow::validateInputs() {
    bool ok = !nameEdit->text().isEmpty() &&
              !pathEdit->text().isEmpty();
    createButton->setEnabled(ok);
}

void StartupWindow::createProject() {
    QString name = nameEdit->text();
    QString basePath = pathEdit->text();

    QDir dir(basePath);

    QString projectPath = basePath + "/" + name;

    if (dir.exists(projectPath)) {
        QMessageBox::warning(this, "Exists", "A project with this name already exists.");
        return;
    }

    if (!dir.mkdir(projectPath)) {
        QMessageBox::critical(this, "Error", "Failed to create project folder.");
        return;
    }

    QString tangleFolder = projectPath + "/.tangle";
    if (!dir.mkdir(tangleFolder)) {
        QMessageBox::critical(this, "Error", "Failed to create .tangle folder.");
        return;
    }

    QString ptrFile = tangleFolder + "/node.ptr";
    QFile file(ptrFile);
    if (!file.open(QIODevice::WriteOnly)) {
        QMessageBox::critical(this, "Error", "Failed to create node.ptr file.");
        return;
    }
    file.close();

    QString modelFilePath = tangleFolder + "/model.py";
    QFile modelFile(modelFilePath);
    if (!modelFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QMessageBox::critical(this, "Error", "Failed to create model.py file.");
        return;
    }

    QString viewFilePath = tangleFolder + "/view.json";
    QFile viewFile(viewFilePath);

    if (!viewFile.open(QIODevice::WriteOnly | QIODevice::Text)) {
        QMessageBox::critical(this, "Error", "Failed to create view.json file.");
        return;
    }

    QJsonObject viewState;
    viewState["canvasZoom"] = 1.0;
    viewState["pyZoom"]     = 0;

    QJsonDocument doc(viewState);
    viewFile.write(doc.toJson(QJsonDocument::Indented));
    viewFile.close();

// -----------
    QTextStream out(&modelFile);
    out << "# This file is auto-generated by TangleML\n";
    out << "def add(a , b): return a + b\n";
    out << "print(add(1, 2))\n";


    modelFile.close();

    emit projectCreated(name, projectPath);
}
